
Executes Seed compliant Docker docker image

<<<<<<< HEAD
The primary purpose of the Seed CLI is to easily enable algorithm execution. The common stumbling blocks for new developers are being able to feed data into and retrieve out fo the containers as a part of execution. The seed run command facilitates this through introspection of the Seed interface indicating exactly what input data is required, allowing for simply specifying the system locations of data and handling all mounting and output validation and capture operations for the developer.

=======
>>>>>>> fb6a11231aab4b25e79657cd9054c4776462152e
seed run -in IMAGE_NAME [-rm] [-q] [-i INPUT_FILE_KEY=INPUT_FILE_VALUE] [-e SETTING_KEY=SETTING_VALUE] [-m MOUNT_KEY=HOST_PATH] [-o OUTPUT_DIRECTORY] [-rep 5] [-s SCHEMA_FILE]

*-in, -imageName* ::
    Docker image name to run

*-i, -inputs* ::
    Specifies the key/value input data values of the seed spec in the format INPUT_FILE_KEY=INPUT_FILE_VALUE

*-e, -setting* ::
    Specifies the key/value setting values of the seed spec in the format SETTING_KEY=VALUE

*-m, -mount* ::
    Specifies the key/value mount values of the seed spec in the format MOUNT_KEY=HOST_PATH

*-o, -outDir* ::
    Job Output Directory Location

*-rm* ::
    Automatically remove the container when it exits (docker run --rm)

*-q, -quiet* ::
    Suppress stdout when running docker image

*-rep, -repetitions* ::
    Run docker image multiple times (i.e. -rep 5 runs the image 5 times)

*-s, -schema* ::
    External Seed metadata schema file; Overrides built in schema to validate side-car metadata files

*EXAMPLE:* +
For an Seed interface with a single inputData.files element with a name of MY_INPUT the seed run command would be as follows:

seed run -in process-file:0.1.0-seed:0.1.0 -i MY_INPUT=/tmp/file_input.txt -o /tmp/outputs

This will volume mount /tmp/file_input.txt as read only and /tmp/outputs into the container, replacing these values with the container relative locations and injecting into the defined args placeholders for consumption by the algorithm.
