'\" t
.\"     Title: seed
.\"    Author: Jonathan Meyer, Mike Holt, Derick Faller, John Tobe
.\" Generator: Asciidoctor 1.5.7.1
.\"      Date: 2018-06-11
.\"    Manual: SEED
.\"    Source: SEED
.\"  Language: English
.\"
.TH "SEED" "1" "2018-06-11" "SEED" "SEED"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
seed \- A test runner for Seed spec compliant algorithms
.SH "SYNOPSIS"
.sp
\fBseed\fP [COMMAND] [OPTIONS]
.SH "DESCRIPTION"
.sp
The Seed team provides a fully featured Command\-Line Interface (CLI) for algorithm developers looking to offer Seed compliant packaging of their jobs. Using the CLI will enable you to quickly iterate without getting bogged down learning how to interface directly with the underlying container technologies (Docker). It also simplifies the process of attaching Seed metadata to your algorithm prior to publish.
.SH "COMMANDS"
.sp
Seed CLI offers sub\-commands that correlate to common operations performed by an algorithm developer. These can be seen from the command\-line by launching the CLI without any arguments.
.SS "build"
.sp
Builds Seed compliant Docker image
.sp
seed build [\-d JOB_DIRECTORY] [\-u USER_NAME \-p PASSWORD]
.sp
\fB\-d, \-directory\fP
.RS 4
Directory containing Seed spec and Dockerfile (default is current directory).
.RE
.sp
\fB\-u, \-user\fP
.RS 4
Username to login if needed to pull images (default anonymous).
.RE
.sp
\fB\-p, \-password\fP
.RS 4
Password to login if needed to pull images (default anonymous).
.RE
.SS "batch"
.sp
Executes Seed compliant Docker image over multiple iterations
.sp
seed batch \-in IMAGE_NAME [\-b BATCH_FILE | \-d BATCH_DIRECTORY] [\-e SETTING=SETTING_VALUE] [\-m MOUNT_KEY=HOST_PATH] [\-o OUTPUT_DIRECTORY]
.sp
\fB\-in, \-imageName\fP
.RS 4
Docker image name to run; Required
.RE
.sp
\fB\-b,  \-batch\fP
.RS 4
Optional file specifying input keys and file mapping for batch processing. Supersedes directory flag.
.RE
.sp
\fB\-d, \-directory\fP
.RS 4
Alternative to batch file; Specifies a directory of files to batch process (default is current directory)
.RE
.sp
\fB\-e,  \-setting\fP
.RS 4
Specifies the key/value setting values of the seed spec in the format SETTING_KEY=VALUE
.RE
.sp
\fB\-m, \-mount\fP
.RS 4
Specifies the key/value mount values of the seed spec in the format MOUNT_KEY=HOST_PATH
.RE
.sp
\fB\-o, \-outDir\fP
.RS 4
Job Output Directory Location
.RE
.sp
\fB\-rm\fP
.RS 4
Automatically remove the container when it exits (docker run \-\-rm)
.RE
.sp
\fB\-s,  \-schema\fP
.RS 4
External Seed metadata schema file; Overrides built in schema to validate side\-car metadata files
.RE
.SS "init"
.sp
Initialize new project with example seed.manifest.json file
.sp
seed init [\-d JOB_DIRECTORY]
.sp
\fB\-d  \-directory\fP
.RS 4
Directory to place seed.manifest.json example. (default is current directory)
.RE
.SS "list"
.sp
Allows for listing of all Seed compliant images residing on the local system
.sp
seed list
.SS "publish"
.sp
Publishes Seed compliant images to remote Docker registry
.sp
seed publish \-in IMAGE_NAME [\-r REGISTRY_NAME] [\-o ORG_NAME] [\-u username] [\-p password] [Conflict Options]
.sp
\fB\-in, \-imageName\fP
.RS 4
Docker image name to publish
.RE
.sp
\fB\-r, \-registry\fP
.RS 4
Specifies a specific registry to publish the image
.RE
.sp
\fB\-o, \-org\fP
.RS 4
Specifies a specific organization to publish the image
.RE
.sp
\fB\-u, \-user\fP
.RS 4
Username to login if needed to publish images (default anonymous).
.RE
.sp
\fB\-p, \-password\fP
.RS 4
Password to login if needed to publish images (default anonymous).
.RE
.sp
\fB\-f\fP
.RS 4
Overwrite remote image if publish conflict found
.RE
.sp
\fBCONFLICT OPTIONS\fP
.RS 4
If the force flag (\-f) is not set, the following options specify how a publish conflict is handled:
    seed publish ... \-f [\-d SEED_DIRECTORY] [\-pp] [\-pm] [\-P] [\-jp] [\-J]
.RE
.sp
\fB\-d, \-directory\fP
.RS 4
Specifies the directory containing the seed.manifest.json and dockerfile to rebuild the image.
.RE
.sp
\fB\-pp\fP
.RS 4
Force Patch version bump of \(aqpackageVersion\(aq in manifest on disk if publish conflict found
.RE
.sp
\fB\-pm\fP
.RS 4
Force Minor version bump of \(aqpackageVersion\(aq in manifest on disk if publish conflict found
.RE
.sp
\fB\-P\fP
.RS 4
Force Major version bump of \(aqpackageVersion\(aq in manifest on disk if publish conflict found
.RE
.sp
\fB\-jp\fP
.RS 4
Force Patch version bump of \(aqjobVersion\(aq in manifest on disk if publish conflict found
.RE
.sp
\fB\-jm\fP
.RS 4
Force Minor version bump of \(aqjobVersion\(aq in manifest on disk if publish conflict found
.RE
.sp
\fB\-J\fP
.RS 4
Force Major version bump of \(aqjobVersion\(aq in manifest on disk if publish conflict found
.RE
.sp
\fBEXAMPLE\fP
    This will build a new image example\-0.2.0\-seed:1.0.0 and publish it to hub.docker.com/geoint
    seed publish \-in example\-0.1.3\-seed:0.1.3 \-r hub.docker.com \-o geoint \-jm \-P
.SS "pull"
.sp
Allows for pulling Seed compliant images from remote Docker registry
.sp
seed pull \-in IMAGE_NAME [\-r REGISTRY_NAME] [\-o ORGANIZATION_NAME] [\-u USER_NAME] [\-p PASSWORD]
.sp
\fB\-in, \-imageName\fP
.RS 4
Docker image name to pull
.RE
.sp
\fB\-r, \-registry\fP
.RS 4
Specifies a specific registry (default is index.docker.io).
.RE
.sp
\fB\-o, \-org\fP
.RS 4
Specifies a specific organization (default is no organization).
.RE
.sp
\fB\-u, \-user\fP
.RS 4
Username to login to remote registry (default anonymous).
.RE
.sp
\fB\-p, \-password\fP
.RS 4
Password to login to remote registry (default anonymous).
.RE
.SS "run"
.sp
Executes Seed compliant Docker docker image
.sp
seed run \-in IMAGE_NAME [\-rm] [\-q] [\-i INPUT_FILE_KEY=INPUT_FILE_VALUE] [\-e SETTING_KEY=SETTING_VALUE] [\-m MOUNT_KEY=HOST_PATH] [\-o OUTPUT_DIRECTORY] [\-rep 5] [\-s SCHEMA_FILE]
.sp
\fB\-in, \-imageName\fP
.RS 4
Docker image name to run
.RE
.sp
\fB\-i, \-inputs\fP
.RS 4
Specifies the key/value input data values of the seed spec in the format INPUT_FILE_KEY=INPUT_FILE_VALUE
.RE
.sp
\fB\-e, \-setting\fP
.RS 4
Specifies the key/value setting values of the seed spec in the format SETTING_KEY=VALUE
.RE
.sp
\fB\-m, \-mount\fP
.RS 4
Specifies the key/value mount values of the seed spec in the format MOUNT_KEY=HOST_PATH
.RE
.sp
\fB\-o, \-outDir\fP
.RS 4
Job Output Directory Location
.RE
.sp
\fB\-rm\fP
.RS 4
Automatically remove the container when it exits (docker run \-\-rm)
.RE
.sp
\fB\-q, \-quiet\fP
.RS 4
Suppress stdout when running docker image
.RE
.sp
\fB\-rep, \-repetitions\fP
.RS 4
Run docker image multiple times (i.e. \-rep 5 runs the image 5 times)
.RE
.sp
\fB\-s, \-schema\fP
.RS 4
External Seed metadata schema file; Overrides built in schema to validate side\-car metadata files
.RE
.SS "search"
.sp
Allows for discovery of Seed compliant images hosted within a Docker registry (default is docker.io)
.sp
seed search [\-r REGISTRY_NAME] [\-o ORGANIZATION_NAME] [\-f FILTER] [\-u Username] [\-p password]
.sp
\fB\-r, \-registry\fP
.RS 4
Specifies a specific registry to search (default is index.docker.io).
.RE
.sp
\fB\-o, \-org\fP
.RS 4
Specifies a specific organization to filter (default is no filter).
.RE
.sp
\fB\-f, \-filter\fP
.RS 4
Specifies a filter to apply (default is no filter).
.RE
.sp
\fB\-u, \-user\fP
.RS 4
Username to login to remote registry (default is anonymous).
.RE
.sp
\fB\-p, \-password\fP
.RS 4
Password to login to remote registry (default is anonymous).
.RE
.SS "validate"
.sp
Validates a Seed spec
.sp
seed validate [\-d MANIFEST_DIRECTORY] [\-s SCHEMA_FILE]
.sp
\fB\-d, \-directory\fP
.RS 4
Specifies the directory in which Seed is located (default is the current directory)
.RE
.sp
\fB\-s, \-schema\fP
.RS 4
External Seed schema file; Overrides built in schema to validate Seed spec against
.RE
.SS "version"
.sp
Prints the current version of Seed spec
.sp
seed version
.SH "AUTHORS"
.sp
Jonathan Meyer
.sp
Mike Holt
.sp
Derick Faller
.sp
John Tobe